export const cabecera = document.querySelector("#cabecera");
export const labelApuesta = document.createElement("label");
export const montoApuesta = document.createElement("input");//es el control numérico que muestra cuanto quieres apostar.
export const labelResultado = document.createElement("label");
export const resultado= document.createElement("input");//es el campo donde se muestra el valor del resultado cuando finaliza la tirada.
export const labelTirada = document.createElement("label");
export const tiradas = document.createElement("input");
export const botonera = document.querySelector("#botonera");
export const pasoTiradas = document.createElement("button");
export const cobrar = document.createElement("button");
export const nuevaPart = document.createElement("button");
